name: Build
on:
  workflow_call:
    inputs:
      actor:
        required: true
        type: string
      repository:
        required: true
        type: string

jobs:
  build-api-image:
    name: Build API Images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ inputs.actor}}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set TAG environment variable
        run: echo "TAG=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
      - name: Lowercase repository name
        run: |
            REPO_LOWER=$(echo "${{ inputs.repository }}" | tr '[:upper:]' '[:lower:]')
            echo "REGISTRY=ghcr.io/$REPO_LOWER" >> $GITHUB_ENV
      - name: Build and push image
        run: |
            docker compose -f .docker/compose.build.yaml --profile build api --parallel
            docker compose -f .docker/compose.build.yaml --profile api push  
  build-client-image:
    name: Build Client Images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ inputs.actor}}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Lowercase repository name
        run: |
            REPO_LOWER=$(echo "${{ inputs.repository }}" | tr '[:upper:]' '[:lower:]')
            echo "REGISTRY=ghcr.io/$REPO_LOWER" >> $GITHUB_ENV
      - name: Set TAG environment variable
        run: echo "TAG=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
      - name: Build and push image
        run: |
          docker compose -f .docker/compose.build.yaml --profile client build --parallel
          docker compose -f .docker/compose.build.yaml --profile client push



    